# Generated by Django 5.0.3 on 2024-03-19 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Barcode",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("date", models.DateField(auto_now=True)),
                ("qte", models.PositiveBigIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name="The",
            fields=[
                (
                    "barcode_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="stock.barcode",
                    ),
                ),
                ("brand", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[("C", "Chaara"), ("M", "Mkarkab")], max_length=20
                    ),
                ),
                ("poid", models.IntegerField()),
                ("ref", models.CharField(max_length=20)),
                (
                    "embalage",
                    models.CharField(
                        choices=[
                            ("C", "carton"),
                            ("Z", "zanbile"),
                            ("Ca", "cadeau"),
                            ("S", "sac"),
                            ("Kh", "khshab"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            bases=("stock.barcode",),
        ),
    ]
