# Generated by Django 5.0.3 on 2024-04-19 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("THE", "THE"),
                            ("PARFUM", "PARFUM"),
                            ("BOKHOUR", "BOKHOUR"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "category_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="stock.category",
                    ),
                ),
                (
                    "sub_cat",
                    models.CharField(
                        choices=[
                            ("CH", "CHAARA"),
                            ("MK", "MKARKAB"),
                            ("LAT", "LATAFA"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
            bases=("stock.category",),
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("date", models.DateField(auto_now_add=True)),
                ("item", models.CharField(max_length=10)),
                ("description", models.CharField(max_length=50)),
                ("qte_entry", models.PositiveIntegerField()),
                ("price", models.FloatField()),
                ("qte_onHand", models.PositiveIntegerField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stock.category"
                    ),
                ),
            ],
        ),
    ]
