# Generated by Django 5.0.7 on 2025-03-21 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "cost_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        related_name="stock",
                        serialize=False,
                        to="stock.item",
                    ),
                ),
                ("current_quantity", models.PositiveIntegerField(default=0)),
                ("unit_by_carton", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="The",
            fields=[
                (
                    "item_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="stock.item",
                    ),
                ),
                (
                    "ref",
                    models.CharField(
                        choices=[
                            ("9366", "9366"),
                            ("9371", "9371"),
                            ("4011", "4011"),
                            ("41022", "41022"),
                            ("3505B", "3505B"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("CHENMEE", "CHENMEE"), ("GUNPOWDER ", "GUNPOWDER ")],
                        max_length=15,
                    ),
                ),
                (
                    "weight",
                    models.IntegerField(
                        choices=[
                            (100, "100g"),
                            (200, "200g"),
                            (500, "500g"),
                            (1000, "1kg"),
                            (2000, "2kg"),
                            (3000, "3kg"),
                        ]
                    ),
                ),
            ],
            bases=("stock.item",),
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("bon_de_livraison", models.CharField(max_length=50)),
                ("qte_total", models.PositiveIntegerField()),
                ("qte_by_carton", models.PositiveIntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReceiptItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("unit_by_carton", models.PositiveSmallIntegerField()),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stock.item"
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="items",
                        to="stock.receipt",
                        verbose_name="Receipt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("threshold", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="stock.stock",
                    ),
                ),
            ],
        ),
    ]
