# Generated by Django 5.0.6 on 2024-06-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parfum",
            name="volum",
            field=models.CharField(
                choices=[
                    ("30 ml", "30 ml"),
                    ("50 ml", "50 ml"),
                    ("100 ml", "100 ml"),
                    ("500 ml", "500 ml"),
                    ("1000 ml", "1000 ml"),
                ],
                max_length=10,
            ),
        ),
    ]
