# Generated by Django 5.0.7 on 2024-07-24 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="current_qte",
        ),
    ]
