# Generated by Django 5.0.7 on 2025-04-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="lead_time",
            field=models.IntegerField(default=7, help_text="Lead time in days"),
        ),
        migrations.AddField(
            model_name="stock",
            name="reorder_point",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="stock",
            name="threshold_amount",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
