# Generated by Django 5.0.3 on 2024-03-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barcode",
            name="code",
            field=models.BigIntegerField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
