# Generated by Django 5.0.3 on 2024-04-24 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parfum",
            fields=[
                (
                    "item_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="stock.item",
                    ),
                ),
                ("sub_brand", models.CharField(max_length=20)),
                (
                    "type",
                    models.CharField(
                        choices=[("MAN", "MAN"), ("WOMEN", "WOMEN"), ("ALL", "ALL")],
                        max_length=10,
                    ),
                ),
                (
                    "volum",
                    models.CharField(
                        choices=[
                            ("100 ml", "100 ml"),
                            ("500 ml", "500 ml"),
                            ("1000 ml", "1000 ml"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
            bases=("stock.item",),
        ),
    ]
