# Generated by Django 5.0.7 on 2024-11-17 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="category",
        ),
        migrations.CreateModel(
            name="The",
            fields=[
                (
                    "item_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="stock.item",
                    ),
                ),
                (
                    "ref",
                    models.CharField(
                        choices=[
                            ("9366", "9366"),
                            ("9371", "9371"),
                            ("4011", "4011"),
                            ("41022", "41022"),
                            ("3505B", "3505B"),
                            ("", ""),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("CHENMEE", "CHENMEE"), ("GUNPOWDER ", "GUNPOWDER ")],
                        max_length=15,
                    ),
                ),
                (
                    "weight",
                    models.CharField(
                        choices=[
                            ("100", "100"),
                            ("200", "200"),
                            ("500", "500"),
                            ("1000", "1000"),
                            ("2000", "2000"),
                            ("3000", "3000"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
            bases=("stock.item",),
        ),
    ]
