# Generated by Django 5.0.7 on 2024-09-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="date",
        ),
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="item",
            name="item",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="the",
            name="weight",
            field=models.CharField(
                choices=[
                    ("100", "100"),
                    ("200", "200"),
                    ("500", "500"),
                    ("1000", "1000"),
                    ("2000", "2000"),
                    ("3000", "3000"),
                ],
                max_length=15,
            ),
        ),
    ]
