# Generated by Django 5.0.7 on 2025-03-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_item_cost_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="lead_time",
            field=models.IntegerField(default=0),
        ),
    ]
