# Generated by Django 5.0.7 on 2024-10-24 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_notification_alter_stockalert_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockalert",
            name="item",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="stock.stock",
            ),
        ),
    ]
