# Generated by Django 5.0.7 on 2024-09-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_remove_item_date_alter_item_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="date",
            field=models.DateField(auto_now=True),
        ),
    ]
