# Generated by Django 5.0.7 on 2024-11-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_remove_item_category_the"),
    ]

    operations = [
        migrations.AlterField(
            model_name="the",
            name="ref",
            field=models.CharField(
                choices=[
                    ("9366", "9366"),
                    ("9371", "9371"),
                    ("4011", "4011"),
                    ("41022", "41022"),
                    ("3505B", "3505B"),
                ],
                max_length=15,
            ),
        ),
    ]
