# Generated by Django 5.0.3 on 2024-03-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0002_alter_barcode_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="the",
            name="embalage",
            field=models.CharField(
                choices=[
                    ("carton", "carton"),
                    ("zanbil", "zanbile"),
                    ("cadeau", "cadeau"),
                    ("sac", "sac"),
                    ("Khshab", "khshab"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="the",
            name="type",
            field=models.CharField(
                choices=[("chaara", "Chaara"), ("mkarkab", "Mkarkab")], max_length=20
            ),
        ),
    ]
