# Generated by Django 5.0.7 on 2025-01-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_item_cost_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.CharField(max_length=100),
        ),
    ]
