# Generated by Django 5.0.7 on 2024-12-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0003_alter_the_ref"),
    ]

    operations = [
        migrations.AlterField(
            model_name="the",
            name="weight",
            field=models.IntegerField(
                choices=[
                    (100, "100g"),
                    (200, "200g"),
                    (500, "500g"),
                    (1000, "1kg"),
                    (2000, "2kg"),
                    (3000, "3kg"),
                ]
            ),
        ),
    ]
