# Generated by Django 5.0.6 on 2024-06-06 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Revendeur",
            fields=[
                ("name", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "account",
                    models.CharField(max_length=13, primary_key=True, serialize=False),
                ),
                ("city", models.CharField(max_length=20)),
                ("matricule", models.CharField(max_length=20)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                ("customer", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "sale_id",
                    models.CharField(
                        max_length=10, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("date", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Cash",
            fields=[
                (
                    "payment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="sale.payment",
                    ),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=6)),
                ("amount_received", models.FloatField(default=False)),
                ("balance", models.FloatField(default=False)),
            ],
            bases=("sale.payment",),
        ),
        migrations.CreateModel(
            name="Cheque",
            fields=[
                (
                    "payment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="sale.payment",
                    ),
                ),
            ],
            bases=("sale.payment",),
        ),
        migrations.AddField(
            model_name="payment",
            name="sale_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sale.sale"
            ),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=13)),
                ("description", models.CharField(max_length=30)),
                ("quantity", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "so_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sale.sale"
                    ),
                ),
            ],
        ),
    ]
