# Generated by Django 5.0.7 on 2024-10-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refund",
            name="reason",
            field=models.CharField(
                choices=[("ERROR", "ERROR"), ("DEFECTIVE", "DEFECTIVE")], max_length=10
            ),
        ),
    ]
