# Generated by Django 5.0.7 on 2024-08-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cash",
            name="amount_received",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
