# Generated by Django 5.0.7 on 2024-07-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
