# Generated by Django 5.0.7 on 2024-10-18 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefundPayment",
            fields=[
                (
                    "payment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="sale.payment",
                    ),
                ),
            ],
            bases=("sale.payment",),
        ),
        migrations.AlterField(
            model_name="saletodealer",
            name="dealer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales",
                to="sale.dealer",
            ),
        ),
    ]
