# Generated by Django 5.0.3 on 2024-05-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sale", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="item",
            field=models.CharField(max_length=13),
        ),
    ]
