# Generated by Django 5.0.7 on 2024-11-05 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ReufundDealerPayment",
            new_name="RefundDealerPayment",
        ),
    ]
