# Generated by Django 5.0.7 on 2024-09-06 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0002_retour"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Retour",
        ),
    ]
