# Generated by Django 5.0.7 on 2024-10-18 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0002_refundpayment_alter_saletodealer_dealer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="refund",
            old_name="sale",
            new_name="sale_id",
        ),
    ]
