# Generated by Django 5.0.3 on 2024-05-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sale", "0002_alter_order_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="customer",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
