# Generated by Django 5.0.7 on 2024-12-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0002_refund_so_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refund",
            name="so_id",
            field=models.IntegerField(),
        ),
    ]
