# Generated by Django 5.0.7 on 2024-09-23 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0002_return_line"),
    ]

    operations = [
        migrations.RenameField(
            model_name="return_line",
            old_name="sale",
            new_name="_sale",
        ),
    ]
