# Generated by Django 5.0.7 on 2024-08-12 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0002_alter_cash_amount_received"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cash",
            name="sale_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="sale.sale"
            ),
        ),
        migrations.AlterField(
            model_name="cheque",
            name="sale_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="sale.sale"
            ),
        ),
    ]
