# Generated by Django 5.0.7 on 2024-09-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0003_rename_sale_return_line__sale"),
    ]

    operations = [
        migrations.AddField(
            model_name="returnsale",
            name="so",
            field=models.CharField(default=None, max_length=30),
        ),
    ]
