# Generated by Django 5.0.7 on 2025-01-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0003_alter_refund_so_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="saletodealer",
            name="matricule",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="saletodealer",
            name="ville",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="refund",
            name="so_id",
            field=models.IntegerField(verbose_name="sale_id"),
        ),
    ]
