# Generated by Django 5.0.3 on 2024-05-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sale", "0003_sale_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="date",
            field=models.DateField(auto_now=True),
        ),
    ]
