# Generated by Django 5.0.7 on 2024-08-12 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0003_alter_cash_sale_id_alter_cheque_sale_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="discount",
        ),
    ]
