# Generated by Django 5.0.7 on 2024-09-10 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0003_delete_retour"),
        ("stock", "0003_item_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("return_date", models.DateField(auto_now_add=True)),
                ("reason", models.TextField()),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="returns",
                        to="sale.sale",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaleReturnItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("refunded", models.BooleanField(default=False)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stock.item"
                    ),
                ),
                (
                    "sale_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sale.salereturn",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="salereturn",
            name="returned_items",
            field=models.ManyToManyField(
                through="sale.SaleReturnItem", to="stock.item"
            ),
        ),
    ]
