# Generated by Django 5.0.7 on 2024-10-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0003_rename_sale_refund_sale_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="refund",
            old_name="sale_id",
            new_name="sale",
        ),
        migrations.AddField(
            model_name="refund",
            name="so",
            field=models.CharField(default="reunfd", max_length=30),
        ),
    ]
