# Generated by Django 5.0.7 on 2024-09-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0004_salereturn_salereturnitem_salereturn_returned_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="salereturn",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
