# Generated by Django 5.0.7 on 2024-10-18 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0005_alter_refund_so"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salepayment",
            name="sale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sale_payments",
                to="sale.sale",
            ),
        ),
    ]
