# Generated by Django 5.0.7 on 2024-09-11 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0005_salereturn_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salereturn",
            name="returned_items",
        ),
        migrations.AlterField(
            model_name="salereturn",
            name="sale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sale_returns",
                to="sale.sale",
            ),
        ),
    ]
