# Generated by Django 5.0.7 on 2024-09-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0006_remove_salereturn_returned_items_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inlineorder",
            name="refunded",
            field=models.BooleanField(default=False),
        ),
    ]
