# Generated by Django 5.0.7 on 2024-10-18 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0006_alter_salepayment_sale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="refund",
            name="amount_refunded",
        ),
    ]
