# Generated by Django 5.0.7 on 2024-10-18 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0007_remove_refund_amount_refunded"),
    ]

    operations = [
        migrations.RenameField(
            model_name="refund_line",
            old_name="returnsale",
            new_name="refund",
        ),
    ]
