# Generated by Django 5.0.7 on 2024-10-18 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0008_rename_returnsale_refund_line_refund"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refund",
            name="sale",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="sale.sale",
            ),
        ),
    ]
