# Generated by Django 5.0.3 on 2024-04-05 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stock", "0002_remove_barcode_qte_alert_alter_barcode_qte_onhand"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "client_id",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Revendeur",
            fields=[
                (
                    "client_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="vente.client",
                    ),
                ),
                ("nom", models.CharField(max_length=30)),
                ("prenom", models.CharField(max_length=30)),
                ("ville", models.CharField(max_length=30)),
                ("matricule", models.CharField(max_length=30)),
            ],
            bases=("vente.client",),
        ),
        migrations.CreateModel(
            name="Vente",
            fields=[
                ("date", models.DateTimeField(auto_created=True)),
                (
                    "commnade",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                (
                    "cliend_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vente.client"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Facture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=50)),
                ("quantite", models.PositiveSmallIntegerField()),
                ("prix", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "id_f",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stock.barcode"
                    ),
                ),
                (
                    "cmd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vente.vente"
                    ),
                ),
            ],
        ),
    ]
