# Generated by Django 5.0.3 on 2024-04-18 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("custom_id", models.CharField(editable=False, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="Revendeur",
            fields=[
                (
                    "customer_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="vente.customer",
                    ),
                ),
                ("nom", models.CharField(max_length=30)),
                ("prenom", models.CharField(max_length=30)),
                ("ville", models.CharField(max_length=30)),
                ("matricule", models.CharField(max_length=30)),
            ],
            bases=("vente.customer",),
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "so",
                    models.CharField(
                        editable=False, max_length=5, primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "c_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vente.customer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CreateOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=30)),
                ("qte", models.PositiveSmallIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stock.barcode"
                    ),
                ),
                (
                    "so_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vente.sale"
                    ),
                ),
            ],
        ),
    ]
