# Generated by Django 5.0.3 on 2024-04-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vente", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="custom_id",
            field=models.CharField(editable=False, max_length=5, unique=True),
        ),
    ]
