# Generated by Django 5.0.3 on 2024-04-08 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0002_remove_barcode_qte_alert_alter_barcode_qte_onhand"),
        ("vente", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_created=True)),
                (
                    "Client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vente.client"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="vente",
            name="cliend_id",
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "sales_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="vente.sales",
                    ),
                ),
                (
                    "order_id",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
            ],
            bases=("vente.sales",),
        ),
        migrations.CreateModel(
            name="OrderDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=50)),
                ("quantite", models.PositiveSmallIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stock.barcode"
                    ),
                ),
                (
                    "order_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vente.order"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Facture",
        ),
        migrations.DeleteModel(
            name="Vente",
        ),
    ]
