# Generated by Django 5.0.3 on 2024-04-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vente", "0002_alter_customer_custom_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="createorder",
            name="price",
            field=models.FloatField(default=0.0),
        ),
    ]
